// <auto-generated />
using System;
using Dhole.Pricing.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dhole.Pricing.Persistence.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomCodeFramework.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_service");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_inbox_messages");

                    b.HasIndex("EventId", "ConsumerService")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("inbox_messages", "pricing");
                });

            modelBuilder.Entity("CustomCodeFramework.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers_json");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Costs.Entities.Cost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("agent_code");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("agent_name");

                    b.Property<string>("CarrierCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("carrier_code");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("carrier_name");

                    b.Property<decimal>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_amount");

                    b.Property<string>("CostDetailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_detail_type");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_type");

                    b.Property<string>("ChargeBasis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("PerShipment")
                        .HasColumnName("charge_basis");

                    b.Property<decimal?>("KgPerCbm")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("kg_per_cbm");

                    b.Property<decimal?>("MinimumCostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_cost_amount");

                    b.Property<decimal?>("MinimumSaleAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_sale_amount");

                    b.Property<string>("ShipmentMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shipment_mode");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("currency_name");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsAccountant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_accountant");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PortCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("port_code");

                    b.Property<Guid?>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_id");

                    b.Property<string>("PortName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("port_name");

                    b.Property<string>("PortRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("port_role");

                    b.Property<string>("PodCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pod_code");

                    b.Property<Guid?>("PodId")
                        .HasColumnType("uuid")
                        .HasColumnName("pod_id");

                    b.Property<string>("PodName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pod_name");

                    b.Property<string>("PoeCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("poe_code");

                    b.Property<Guid?>("PoeId")
                        .HasColumnType("uuid")
                        .HasColumnName("poe_id");

                    b.Property<string>("PoeName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("poe_name");

                    b.Property<string>("PolCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pol_code");

                    b.Property<Guid?>("PolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pol_id");

                    b.Property<string>("PolName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pol_name");

                    b.Property<decimal>("SaleAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("UtilityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("utility_amount");

                    b.HasKey("Id")
                        .HasName("p_k_costs");

                    b.HasIndex("AgentId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("CostDetailType");

                    b.HasIndex("CostType");

                    b.HasIndex("ChargeBasis");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ShipmentMode");

                    b.HasIndex("IsAccountant");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("PortId");

                    b.HasIndex("PortRole");

                    b.HasIndex("PolId");

                    b.HasIndex("PoeId");

                    b.HasIndex("PodId");

                    b.HasIndex("CostType", "CostDetailType", "CarrierId", "AgentId", "PortId", "PortRole", "PolId", "PoeId", "PodId", "ShipmentMode", "ChargeBasis", "IsAccountant", "Name", "CurrencyId")
                        .IsUnique()
                        .HasDatabaseName("ix_costs_template_unique")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Costs", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Costs.Entities.CostIncoterm", b =>
                {
                    b.Property<Guid>("CostId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_id");

                    b.Property<Guid>("IncotermId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoterm_id");

                    b.Property<string>("IncotermCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("incoterm_code");

                    b.Property<string>("IncotermName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("incoterm_name");

                    b.HasKey("CostId", "IncotermId");

                    b.HasIndex("IncotermCode");

                    b.HasIndex("IncotermId");

                    b.ToTable("CostIncoterms", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Imports.Entities.ImportFclRates", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_code");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("agent_name");

                    b.Property<string>("AgentSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("agent_slug");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("carrier");

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("carrier_code");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("carrier_name");

                    b.Property<string>("CarrierSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("carrier_slug");

                    b.Property<string>("Commodity")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("commodity");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("container_type");

                    b.Property<string>("ContainerTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("container_type_code");

                    b.Property<Guid>("ContainerTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_type_id");

                    b.Property<string>("ContainerTypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("container_type_name");

                    b.Property<string>("ContainerTypeSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("container_type_slug");

                    b.Property<Guid?>("CreatedAsRateHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_as_rate_header_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("currency_name");

                    b.Property<string>("CurrencySlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("currency_slug");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<decimal?>("DestinationCharges")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("destination_charges");

                    b.Property<Guid>("ExtractionRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_record_id");

                    b.Property<int>("FreeDays")
                        .HasColumnType("integer")
                        .HasColumnName("free_days");

                    b.Property<decimal>("Freight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("freight");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<string>("ImportProfileCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("import_profile_code");

                    b.Property<Guid>("ImportProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_profile_id");

                    b.Property<string>("ImportProfileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("import_profile_name");

                    b.Property<string>("ImportProfileSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("import_profile_slug");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("Margin")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("margin");

                    b.Property<decimal?>("OceanFreight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ocean_freight");

                    b.Property<decimal?>("OriginCharges")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("origin_charges");

                    b.Property<string>("Pod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pod");

                    b.Property<string>("PodCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pod_code");

                    b.Property<Guid?>("PodId")
                        .HasColumnType("uuid")
                        .HasColumnName("pod_id");

                    b.Property<string>("PodName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pod_name");

                    b.Property<string>("PodSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pod_slug");

                    b.Property<string>("Poe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poe");

                    b.Property<string>("PoeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poe_code");

                    b.Property<Guid>("PoeId")
                        .HasColumnType("uuid")
                        .HasColumnName("poe_id");

                    b.Property<string>("PoeName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("poe_name");

                    b.Property<string>("PoeSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("poe_slug");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pol");

                    b.Property<string>("PolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pol_code");

                    b.Property<Guid>("PolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pol_id");

                    b.Property<string>("PolName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pol_name");

                    b.Property<string>("PolSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pol_slug");

                    b.Property<decimal?>("Profit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("profit");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data_json");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<string>("SpaceComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("space_comment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Surcharges")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("surcharges");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_cost");

                    b.Property<decimal?>("TotalSale")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_sale");

                    b.Property<int?>("TransitDays")
                        .HasColumnType("integer")
                        .HasColumnName("transit_days");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("UsedAsRateCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_as_rate_count");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("p_k_import_fcl_rates");

                    b.HasIndex("ExtractionRecordId")
                        .IsUnique();

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("Status");

                    b.HasIndex("CarrierId", "PolId", "PoeId", "PodId", "ContainerTypeId");

                    b.ToTable("ImportFclRates", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Imports.Entities.PricingImportFromExtractionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EmailExtractionJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_extraction_job_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("ExternalRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_request_id");

                    b.Property<Guid>("ExtractionExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_execution_id");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("lease_owner");

                    b.Property<int>("MaxAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_attempt_count");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("PersistedRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("persisted_rows");

                    b.Property<Guid>("PricingImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_import_id");

                    b.Property<int>("SkippedRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("skipped_rows");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("p_k_pricing_import_from_extraction_jobs");

                    b.HasIndex("EmailExtractionJobId");

                    b.HasIndex("ExternalRequestId")
                        .IsUnique();

                    b.HasIndex("ExtractionExecutionId");

                    b.HasIndex("PricingImportId");

                    b.HasIndex("Status", "LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_pricing_extraction_jobs_lease");

                    b.HasIndex("Status", "NextAttemptAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_pricing_extraction_jobs_queue");

                    b.ToTable("PricingImportFromExtractionJobs", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateContainerAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContainerTypeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("container_type_code");

                    b.Property<Guid>("ContainerTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_type_id");

                    b.Property<string>("ContainerTypeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("container_type_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RateHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_header_id");

                    b.HasKey("Id")
                        .HasName("p_k_rate_container_allocations");

                    b.HasIndex("ContainerTypeId")
                        .HasDatabaseName("i_x_rate_container_allocations_container_type_id");

                    b.HasIndex("RateHeaderId")
                        .HasDatabaseName("i_x_rate_container_allocations_rate_header_id");

                    b.HasIndex("RateHeaderId", "ContainerTypeId")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_container_allocations_rate_container");

                    b.ToTable("RateContainerAllocations", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_amount");

                    b.Property<string>("CostDetailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_detail_type");

                    b.Property<Guid?>("CostId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_id");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_type");

                    b.Property<string>("ChargeBasis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("PerShipment")
                        .HasColumnName("charge_basis");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("currency_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<Guid>("RateHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_header_id");

                    b.Property<decimal>("SaleAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_amount");

                    b.Property<decimal>("UtilityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("utility_amount");

                    b.HasKey("Id")
                        .HasName("p_k_rate_details");

                    b.HasIndex("CostDetailType");

                    b.HasIndex("CostId");

                    b.HasIndex("CostType");

                    b.HasIndex("ChargeBasis");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("RateHeaderId")
                        .HasDatabaseName("i_x_rate_details_rate_header_id");

                    b.HasIndex("RateHeaderId", "CostId", "Name", "CostDetailType", "CostType", "CurrencyId")
                        .HasDatabaseName("ix_rate_details_lookup");

                    b.ToTable("RateDetails", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("agent_code");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("agent_name");

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("carrier_code");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("carrier_name");

                    b.Property<string>("ClientName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("client_name");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<string>("ClosedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("closed_reason");

                    b.Property<int>("ContainerQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("container_quantity");

                    b.Property<string>("ContainerTypeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("container_type_code");

                    b.Property<Guid>("ContainerTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_type_id");

                    b.Property<string>("ContainerTypeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("container_type_name");

                    b.Property<string>("CargoLinesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("cargo_lines_json");

                    b.Property<decimal>("ChargeableQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(1m)
                        .HasColumnName("chargeable_quantity");

                    b.Property<decimal>("KgPerCbm")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(500m)
                        .HasColumnName("kg_per_cbm");

                    b.Property<string>("ShipmentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Fcl")
                        .HasColumnName("shipment_mode");

                    b.Property<int>("TotalPackages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_packages");

                    b.Property<int>("TotalPallets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_pallets");

                    b.Property<decimal>("TotalVolumeCbm")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_volume_cbm");

                    b.Property<decimal>("TotalWeightKg")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_weight_kg");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("currency_name");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Excludes")
                        .HasColumnType("text")
                        .HasColumnName("excludes");

                    b.Property<int>("FreeDays")
                        .HasColumnType("integer")
                        .HasColumnName("free_days");

                    b.Property<string>("IdtraNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idtra_number");

                    b.Property<string>("Includes")
                        .HasColumnType("text")
                        .HasColumnName("includes");

                    b.Property<string>("IncotermCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("incoterm_code");

                    b.Property<Guid?>("IncotermId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoterm_id");

                    b.Property<string>("IncotermName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("incoterm_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MarginPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("margin_percentage");

                    b.Property<string>("PodCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pod_code");

                    b.Property<Guid>("PodId")
                        .HasColumnType("uuid")
                        .HasColumnName("pod_id");

                    b.Property<string>("PodName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pod_name");

                    b.Property<string>("PoeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("poe_code");

                    b.Property<Guid>("PoeId")
                        .HasColumnType("uuid")
                        .HasColumnName("poe_id");

                    b.Property<string>("PoeName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("poe_name");

                    b.Property<string>("PolCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pol_code");

                    b.Property<Guid>("PolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pol_id");

                    b.Property<string>("PolName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pol_name");

                    b.Property<string>("QuoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quo_number");

                    b.Property<string>("RateCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("rate_code");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rate_name");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Tariff")
                        .HasColumnName("rate_type");

                    b.Property<bool>("RequiredApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("required_approval");

                    b.Property<Guid?>("SourceImportFclRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_import_fcl_rate_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectTo")
                        .HasColumnType("text")
                        .HasColumnName("subject_to");

                    b.Property<decimal>("TotalCostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_cost_amount");

                    b.Property<decimal>("TotalSaleAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_sale_amount");

                    b.Property<decimal>("TotalUtilityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_utility_amount");

                    b.Property<string>("TransitTime")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("transit_time");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("p_k_rate_headers");

                    b.HasIndex("AgentId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("ShipmentMode");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("IdtraNumber");

                    b.HasIndex("IncotermId");

                    b.HasIndex("RateType");

                    b.HasIndex("PodId");

                    b.HasIndex("PoeId");

                    b.HasIndex("PolId");

                    b.HasIndex("QuoNumber");

                    b.HasIndex("RateCode")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_headers_rate_code");

                    b.HasIndex("RequiredApproval");

                    b.HasIndex("SourceImportFclRateId")
                        .HasDatabaseName("ix_rate_headers_source_import_fcl_rate_id");

                    b.HasIndex("Status");

                    b.HasIndex("ValidFrom");

                    b.HasIndex("ValidTo");

                    b.HasIndex("AgentId", "CarrierId", "PolId", "PoeId", "PodId", "ContainerTypeId", "CurrencyId", "Status", "ValidFrom", "ValidTo")
                        .HasDatabaseName("ix_rate_headers_valid_lookup");

                    b.ToTable("RateHeaders", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateTermItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_rate_term_items");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("RateTermItems", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Costs.Entities.CostIncoterm", b =>
                {
                    b.HasOne("Dhole.Pricing.Domain.Costs.Entities.Cost", null)
                        .WithMany("Incoterms")
                        .HasForeignKey("CostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_cost_incoterms_costs_cost_id");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateContainerAllocation", b =>
                {
                    b.HasOne("Dhole.Pricing.Domain.Rates.Entities.RateHeader", null)
                        .WithMany("RateContainers")
                        .HasForeignKey("RateHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rate_container_allocations__rate_headers_rate_header_id");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateDetail", b =>
                {
                    b.HasOne("Dhole.Pricing.Domain.Rates.Entities.RateHeader", null)
                        .WithMany("RateDetails")
                        .HasForeignKey("RateHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rate_details__rate_headers_rate_header_id");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Costs.Entities.Cost", b =>
                {
                    b.Navigation("Incoterms");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateHeader", b =>
                {
                    b.Navigation("RateContainers");

                    b.Navigation("RateDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
