// <auto-generated />
using System;
using Dhole.Pricing.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dhole.Pricing.Persistence.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomCodeFramework.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_service");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_inbox_messages");

                    b.HasIndex("EventId", "ConsumerService")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("inbox_messages", "pricing");
                });

            modelBuilder.Entity("CustomCodeFramework.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers_json");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Costs.Entities.Cost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("agent_code");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("agent_name");

                    b.Property<string>("CarrierCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("carrier_code");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("carrier_name");

                    b.Property<decimal>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_amount");

                    b.Property<string>("CostDetailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_detail_type");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("currency_name");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsAccountant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_accountant");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PortCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("port_code");

                    b.Property<Guid?>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_id");

                    b.Property<string>("PortName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("port_name");

                    b.Property<string>("PortRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("port_role");

                    b.Property<decimal>("SaleAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("UtilityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("utility_amount");

                    b.HasKey("Id")
                        .HasName("p_k_costs");

                    b.HasIndex("AgentId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("CostDetailType");

                    b.HasIndex("CostType");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("IsAccountant");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("PortId");

                    b.HasIndex("PortRole");

                    b.HasIndex("CostType", "CostDetailType", "CarrierId", "AgentId", "PortId", "PortRole", "IsAccountant", "Name", "CurrencyId")
                        .IsUnique()
                        .HasDatabaseName("ix_costs_template_unique")
                        .HasFilter("is_deleted = false");

                    b.ToTable("Costs", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Imports.Entities.ImportFclRates", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_code");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("agent_name");

                    b.Property<string>("AgentSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("agent_slug");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("carrier");

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("carrier_code");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("carrier_name");

                    b.Property<string>("CarrierSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("carrier_slug");

                    b.Property<string>("Commodity")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("commodity");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("container_type");

                    b.Property<string>("ContainerTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("container_type_code");

                    b.Property<Guid>("ContainerTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_type_id");

                    b.Property<string>("ContainerTypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("container_type_name");

                    b.Property<string>("ContainerTypeSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("container_type_slug");

                    b.Property<Guid?>("CreatedAsRateHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_as_rate_header_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("currency_name");

                    b.Property<string>("CurrencySlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("currency_slug");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<decimal?>("DestinationCharges")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("destination_charges");

                    b.Property<Guid>("ExtractionRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_record_id");

                    b.Property<int>("FreeDays")
                        .HasColumnType("integer")
                        .HasColumnName("free_days");

                    b.Property<decimal>("Freight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("freight");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<string>("ImportProfileCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("import_profile_code");

                    b.Property<Guid>("ImportProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_profile_id");

                    b.Property<string>("ImportProfileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("import_profile_name");

                    b.Property<string>("ImportProfileSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("import_profile_slug");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("Margin")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("margin");

                    b.Property<decimal?>("OceanFreight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ocean_freight");

                    b.Property<decimal?>("OriginCharges")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("origin_charges");

                    b.Property<string>("Pod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pod");

                    b.Property<string>("PodCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pod_code");

                    b.Property<Guid>("PodId")
                        .HasColumnType("uuid")
                        .HasColumnName("pod_id");

                    b.Property<string>("PodName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pod_name");

                    b.Property<string>("PodSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pod_slug");

                    b.Property<string>("Poe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poe");

                    b.Property<string>("PoeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poe_code");

                    b.Property<Guid>("PoeId")
                        .HasColumnType("uuid")
                        .HasColumnName("poe_id");

                    b.Property<string>("PoeName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("poe_name");

                    b.Property<string>("PoeSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("poe_slug");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pol");

                    b.Property<string>("PolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pol_code");

                    b.Property<Guid>("PolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pol_id");

                    b.Property<string>("PolName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pol_name");

                    b.Property<string>("PolSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pol_slug");

                    b.Property<decimal?>("Profit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("profit");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data_json");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Surcharges")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("surcharges");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_cost");

                    b.Property<decimal?>("TotalSale")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_sale");

                    b.Property<int?>("TransitDays")
                        .HasColumnType("integer")
                        .HasColumnName("transit_days");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("UsedAsRateCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_as_rate_count");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("p_k_import_fcl_rates");

                    b.HasIndex("ExtractionRecordId")
                        .IsUnique();

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("Status");

                    b.HasIndex("CarrierId", "PolId", "PoeId", "PodId", "ContainerTypeId");

                    b.ToTable("ImportFclRates", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_amount");

                    b.Property<string>("CostDetailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_detail_type");

                    b.Property<Guid?>("CostId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_id");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_type");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("currency_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<Guid>("RateHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_header_id");

                    b.Property<decimal>("SaleAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_amount");

                    b.Property<decimal>("UtilityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("utility_amount");

                    b.HasKey("Id")
                        .HasName("p_k_rate_details");

                    b.HasIndex("CostDetailType");

                    b.HasIndex("CostId");

                    b.HasIndex("CostType");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("RateHeaderId")
                        .HasDatabaseName("i_x_rate_details_rate_header_id");

                    b.HasIndex("RateHeaderId", "CostId", "Name", "CostDetailType", "CostType", "CurrencyId")
                        .HasDatabaseName("ix_rate_details_lookup");

                    b.ToTable("RateDetails", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("agent_code");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("agent_name");

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("carrier_code");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("carrier_name");

                    b.Property<string>("ContainerTypeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("container_type_code");

                    b.Property<Guid>("ContainerTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_type_id");

                    b.Property<string>("ContainerTypeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("container_type_name");

                    b.Property<int>("ContainerQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("container_quantity");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("currency_name");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<int>("FreeDays")
                        .HasColumnType("integer")
                        .HasColumnName("free_days");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MarginPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("margin_percentage");

                    b.Property<string>("PodCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pod_code");

                    b.Property<Guid>("PodId")
                        .HasColumnType("uuid")
                        .HasColumnName("pod_id");

                    b.Property<string>("PodName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pod_name");

                    b.Property<string>("PoeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("poe_code");

                    b.Property<Guid>("PoeId")
                        .HasColumnType("uuid")
                        .HasColumnName("poe_id");

                    b.Property<string>("PoeName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("poe_name");

                    b.Property<string>("PolCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pol_code");

                    b.Property<Guid>("PolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pol_id");

                    b.Property<string>("PolName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pol_name");

                    b.Property<string>("RateCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rate_code");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rate_name");

                    b.Property<bool>("RequiredApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("required_approval");

                    b.Property<Guid?>("SourceImportFclRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_import_fcl_rate_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_cost_amount");

                    b.Property<decimal>("TotalSaleAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_sale_amount");

                    b.Property<decimal>("TotalUtilityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_utility_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("p_k_rate_headers");

                    b.HasIndex("AgentId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PodId");

                    b.HasIndex("PoeId");

                    b.HasIndex("PolId");

                    b.HasIndex("RateCode")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_headers_rate_code");

                    b.HasIndex("RequiredApproval");

                    b.HasIndex("SourceImportFclRateId")
                        .HasDatabaseName("ix_rate_headers_source_import_fcl_rate_id");

                    b.HasIndex("Status");

                    b.HasIndex("ValidFrom");

                    b.HasIndex("ValidTo");

                    b.HasIndex("AgentId", "CarrierId", "PolId", "PoeId", "PodId", "ContainerTypeId", "CurrencyId", "Status", "ValidFrom", "ValidTo")
                        .HasDatabaseName("ix_rate_headers_valid_lookup");

                    b.ToTable("RateHeaders", "pricing");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateDetail", b =>
                {
                    b.HasOne("Dhole.Pricing.Domain.Rates.Entities.RateHeader", null)
                        .WithMany("RateDetails")
                        .HasForeignKey("RateHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rate_details__rate_headers_rate_header_id");
                });

            modelBuilder.Entity("Dhole.Pricing.Domain.Rates.Entities.RateHeader", b =>
                {
                    b.Navigation("RateDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
