namespace Dhole.Pricing.Contracts.Rates.Request;

public sealed record CreateRateRequest(
    Guid? SourceImportFclRateId,
    Guid? AgentId,
    string? AgentName,
    string? AgentCode,
    Guid? CarrierId,
    string? CarrierName,
    string? CarrierCode,
    Guid PolId,
    string PolName,
    string PolCode,
    Guid PoeId,
    string PoeName,
    string PoeCode,
    Guid PodId,
    string PodName,
    string PodCode,
    Guid ContainerTypeId,
    string ContainerTypeName,
    string ContainerTypeCode,
    Guid CurrencyId,
    string CurrencyName,
    string CurrencyCode,
    int FreeDays,
    DateTime ValidFrom,
    DateTime ValidTo,
    IReadOnlyCollection<CreateRateDetailRequest> Details,
    int ContainerQuantity = 1,
    string? ClientName = null,
    string? IdtraNumber = null,
    string? QuoNumber = null,
    string? Includes = null,
    string? SubjectTo = null,
    string? Excludes = null,
    int? TransitDays = null
);
