namespace Dhole.Pricing.Contracts.Competitors;

public sealed record CompetitorRateObservationDto(
    Guid Id,
    Guid CompetitorTariffId,
    string CompetitorCompanyName,
    Guid? IncotermId,
    string? IncotermCode,
    Guid? PolId,
    string? PolName,
    string? PolCode,
    Guid? PoeId,
    string? PoeName,
    string? PoeCode,
    Guid? PodId,
    string? PodName,
    string? PodCode,
    Guid? CarrierId,
    string? CarrierName,
    string? CarrierCode,
    Guid? ContainerTypeId,
    string? ContainerTypeCode,
    string ShipmentMode,
    string Currency,
    decimal? OriginalAmount,
    string? NormalizedCurrency,
    decimal? NormalizedAmount,
    DateTime ValidFrom,
    DateTime ValidTo,
    decimal ExtractionConfidence,
    decimal NormalizationConfidence,
    bool IsUsable,
    bool NeedsReview
);
