namespace Dhole.Pricing.Contracts.Rates.Response;

public sealed record RateDto(
    Guid Id,
    Guid? SourceImportFclRateId,
    Guid? AgentId,
    string? AgentName,
    string? AgentCode,
    Guid? CarrierId,
    string? CarrierName,
    string? CarrierCode,
    Guid PolId,
    string PolName,
    string PolCode,
    Guid PoeId,
    string PoeName,
    string PoeCode,
    Guid PodId,
    string PodName,
    string PodCode,
    Guid ContainerTypeId,
    string ContainerTypeName,
    string ContainerTypeCode,
    Guid CurrencyId,
    string CurrencyName,
    string CurrencyCode,
    int FreeDays,
    DateTime ValidFrom,
    DateTime ValidTo,
    decimal TotalCostAmount,
    decimal TotalSaleAmount,
    decimal TotalUtilityAmount,
    decimal MarginPercentage,
    bool RequiredApproval,
    string Status,
    IReadOnlyCollection<RateDetailDto> RateDetails
);
