namespace Dhole.Pricing.Contracts.Costs.Response;

public sealed record CostDto(
    Guid Id,
    string Name,
    string CostType,
    string CostDetailType,
    Guid? CarrierId,
    string? CarrierName,
    string? CarrierCode,
    Guid? AgentId,
    string? AgentName,
    string? AgentCode,
    Guid? PortId,
    string? PortName,
    string? PortCode,
    string? PortRole,
    Guid CurrencyId,
    string CurrencyName,
    string CurrencyCode,
    decimal CostAmount,
    decimal SaleAmount,
    decimal UtilityAmount,
    string? Notes,
    bool IsAccountant,
    bool IsActive,
    IReadOnlyCollection<CostIncotermDto> Incoterms,
    Guid? PolId = null,
    string? PolName = null,
    string? PolCode = null,
    Guid? PoeId = null,
    string? PoeName = null,
    string? PoeCode = null,
    Guid? PodId = null,
    string? PodName = null,
    string? PodCode = null,
    string? ShipmentMode = null,
    string ChargeBasis = "PerShipment",
    decimal? MinimumCostAmount = null,
    decimal? MinimumSaleAmount = null,
    decimal? KgPerCbm = null,
    IReadOnlyCollection<CostServiceDto>? Services = null
);
