using CustomCodeFramework.Redis.Streams.Abstractions;
using CustomCodeFramework.Redis.Streams.Messages;
using Dhole.Pricing.Application.Imports;

namespace Dhole.Pricing.Worker.Streams;

internal sealed class AgentOceanFreightRatesExtractedStreamHandler(
    AgentOceanFreightImportService importService,
    ILogger<AgentOceanFreightRatesExtractedStreamHandler> logger)
    : IRedisStreamMessageHandler
{
    public string MessageType => "agent.ocean-freight-rates.extracted";

    public async Task HandleAsync(
        RedisStreamEnvelope envelope,
        CancellationToken cancellationToken = default)
    {
        var integrationEvent =
            PricingExtractionStreamPayloadReader.Read<AgentOceanFreightRatesExtractedIntegrationEvent>(
                envelope);

        if (integrationEvent.ResultId == Guid.Empty
            || integrationEvent.ExecutionId == Guid.Empty)
        {
            throw new InvalidOperationException(
                "El evento de extracción de Agent no contiene ResultId/ExecutionId.");
        }

        if (string.IsNullOrWhiteSpace(integrationEvent.DataJson))
        {
            // Events generated by older Agent builds did not contain DataJson.
            // Acknowledge them instead of poisoning the pricing stream.
            logger.LogWarning(
                "Ignoring legacy Agent extraction event {ResultId}: payload has no DataJson.",
                integrationEvent.ResultId);
            return;
        }

        var persisted = await importService.PersistAsync(
            integrationEvent.ResultId,
            integrationEvent.ExecutionId,
            integrationEvent.DataJson,
            integrationEvent.ExtractedAtUtc,
            cancellationToken);

        logger.LogInformation(
            "Agent extraction imported into FCL rates. Result={ResultId} Execution={ExecutionId} Created={CreatedRows} Skipped={SkippedRows} ExtractedAt={ExtractedAtUtc}",
            integrationEvent.ResultId,
            integrationEvent.ExecutionId,
            persisted.CreatedRows,
            persisted.SkippedRows,
            integrationEvent.ExtractedAtUtc);
    }

    private sealed record AgentOceanFreightRatesExtractedIntegrationEvent(
        Guid ResultId,
        Guid ExecutionId,
        Guid ProviderId,
        string ResultType,
        string SchemaVersion,
        string DataJson,
        DateTime ExtractedAtUtc);
}
