namespace Dhole.Pricing.Contracts.Costs.Request;

public sealed record CreateCostRequest(
    string Name,
    string CostType,
    string CostDetailType,
    Guid? CarrierId,
    string? CarrierName,
    string? CarrierCode,
    Guid? AgentId,
    string? AgentName,
    string? AgentCode,
    Guid? PortId,
    string? PortName,
    string? PortCode,
    string? PortRole,
    Guid CurrencyId,
    string CurrencyName,
    string CurrencyCode,
    decimal CostAmount,
    decimal SaleAmount,
    string? Notes,
    bool IsAccountant = false,
    IReadOnlyCollection<CostIncotermRequest>? Incoterms = null,
    Guid? PolId = null,
    string? PolName = null,
    string? PolCode = null,
    Guid? PoeId = null,
    string? PoeName = null,
    string? PoeCode = null,
    Guid? PodId = null,
    string? PodName = null,
    string? PodCode = null,
    string? ShipmentMode = null,
    string ChargeBasis = "PerShipment",
    decimal? MinimumCostAmount = null,
    decimal? MinimumSaleAmount = null,
    decimal? KgPerCbm = null,
    IReadOnlyCollection<CostServiceRequest>? Services = null
);
