namespace Dhole.Pricing.Application.Abstractions.Mongo;

public interface IRateHeaderChangeSnapshotWriter
{
    Task WriteAsync(
        Guid eventId,
        string eventName,
        string entityType,
        Guid entityId,
        Guid? sourceImportFclRateId,
        Guid agentId,
        string agentNameSnapshot,
        string agentCodeSnapshot,
        Guid carrierId,
        string carrierNameSnapshot,
        string carrierCodeSnapshot,
        Guid polId,
        string polNameSnapshot,
        string polCodeSnapshot,
        Guid poeId,
        string poeNameSnapshot,
        string poeCodeSnapshot,
        Guid podId,
        string podNameSnapshot,
        string podCodeSnapshot,
        Guid containerTypeId,
        string containerTypeNameSnapshot,
        string containerTypeCodeSnapshot,
        Guid currencyId,
        string currencyNameSnapshot,
        string currencyCodeSnapshot,
        int freeDays,
        DateTime validFrom,
        DateTime validTo,
        decimal totalCostAmount,
        decimal totalSaleAmount,
        decimal totalUtilityAmount,
        decimal marginPercentage,
        bool requiredApproval,
        string status,
        string? rateDetailsJson,
        string action,
        string? previousValueJson,
        string? newValueJson,
        Guid? changedBy,
        DateTime changedAtUtc,
        Guid? correlationId,
        CancellationToken cancellationToken = default
    );
}
